##API Encryption
API-Encryption: "xxxxxx"
##WIFI AP
Wifi_SSID: "xxxxxx"
##WIFI PASSWORD
Wifi_pass: "xxxxxx"
##OTA PASSWORD
OTA_pass: "xxxxxx"
##AP PASSWORD
AP_pass: "xxxxxx"
## LAT & LON
home_location:"xxxxxx"
latitude: "xxxxxx"
longitude: "xxxxxx"
