on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3
      - name: 📦 Create zip file for the packages esphome lovelace www
        run: |
          cd "${{ github.workspace }}/elettrodomestici_2023"
          zip -r elettrodomestici_2023.zip packages lovelace www
      - name: 📤 Upload the zip file as a release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ github.workspace }}//elettrodomestici_2023/elettrodomestici_2023.zip"
          asset_name: elettrodomestici_2023.zip
          tag: ${{ github.ref }}
          overwrite: true
